
extern zend_class_entry *phalcon_encryption_security_uuid_sysnodeprovider_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_Uuid_SysNodeProvider);

PHP_METHOD(Phalcon_Encryption_Security_Uuid_SysNodeProvider, getNode);
PHP_METHOD(Phalcon_Encryption_Security_Uuid_SysNodeProvider, isValidNode);

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_encryption_security_uuid_sysnodeprovider_getnode, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_encryption_security_uuid_sysnodeprovider_isvalidnode, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, node, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_uuid_sysnodeprovider_method_entry) {
	PHP_ME(Phalcon_Encryption_Security_Uuid_SysNodeProvider, getNode, arginfo_phalcon_encryption_security_uuid_sysnodeprovider_getnode, ZEND_ACC_PUBLIC)
	PHP_ME(Phalcon_Encryption_Security_Uuid_SysNodeProvider, isValidNode, arginfo_phalcon_encryption_security_uuid_sysnodeprovider_isvalidnode, ZEND_ACC_PRIVATE)
	PHP_FE_END
};
