
extern zend_class_entry *phalcon_encryption_security_uuid_timebaseduuidinterface_ce;

ZEPHIR_INIT_CLASS(Phalcon_Encryption_Security_Uuid_TimeBasedUuidInterface);

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_phalcon_encryption_security_uuid_timebaseduuidinterface_getdatetime, 0, 0, DateTimeImmutable, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_phalcon_encryption_security_uuid_timebaseduuidinterface_getnode, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(phalcon_encryption_security_uuid_timebaseduuidinterface_method_entry) {
	PHP_ABSTRACT_ME(Phalcon_Encryption_Security_Uuid_TimeBasedUuidInterface, getDateTime, arginfo_phalcon_encryption_security_uuid_timebaseduuidinterface_getdatetime)
	PHP_ABSTRACT_ME(Phalcon_Encryption_Security_Uuid_TimeBasedUuidInterface, getNode, arginfo_phalcon_encryption_security_uuid_timebaseduuidinterface_getnode)
	PHP_FE_END
};
