# This file is part of Phalcon.
#
# (c) Phalcon Team <team@phalcon.io>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: "[Windows] Build & Publish Release DLLs"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  windows:
    name: "Build / PHP-${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.arch }}"
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        arch:
          - x64
          - x86
        ts:
          - nts
          - ts

    steps:
      - name: Checkout Phalcon
        uses: actions/checkout@v4

      - name: Extract Phalcon Version
        shell: powershell
        run: |
          chcp 65001
          $r = Select-String -Path build/phalcon/php_phalcon.h -Pattern 'PHP_PHALCON_VERSION\s+"(.*)"'
          $s = $r.Matches[0].Groups[1]
          echo "PHALCON_VERSION=$s" >> $env:GITHUB_ENV

      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@v0.11
        with:
          version: ${{ matrix.php }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          deps: zlib

      - name: Generate build folder
        run: |
          cd build/
          php gen-build.php

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          toolset: ${{ steps.setup-php.outputs.toolset }}

      - name: Phpize
        run: |
          cd build/phalcon/
          phpize

      - name: Configure
        run: |
          cd build/phalcon/
          ./configure --enable-phalcon --with-prefix=${{ steps.setup-php.outputs.prefix }}

      - name: Make
        run: |
          cd build/phalcon/
          nmake

      - name: Prepare Release Asset
        shell: powershell
        run: |
          chcp 65001

          $dir = (Get-Location).Path + '\build\phalcon\'
          if ('x64' -eq '${{ matrix.arch }}') { $dir = $dir + 'x64\' }
          $dir = $dir + 'Release'
          if ('ts' -eq '${{ matrix.ts }}') { $dir = $dir + '_TS' }

          $from = $dir + '\php_phalcon.dll'

          $artifactName = 'php_phalcon-${{ env.PHALCON_VERSION }}-php${{ matrix.php }}-${{ matrix.ts }}-windows-${{ matrix.arch }}'

          $dest = '.\release-asset'
          New-Item $dest -ItemType Directory -Force | Out-Null
          Copy-Item $from -Destination "$dest\php_phalcon.dll"
          Copy-Item "LICENSE.txt" -Destination "$dest\"

          Set-Location $dest
          & 7z a "..\${artifactName}.zip" *

          echo "ASSET_PATH=${artifactName}.zip" >> $env:GITHUB_ENV

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_PATH }}
